[2025-04-09T15:22:52.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T15:22:52.864+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-04-09T15:22:50.850962+00:00 [queued]>
[2025-04-09T15:22:52.875+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-04-09T15:22:50.850962+00:00 [queued]>
[2025-04-09T15:22:52.875+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-09T15:22:53.095+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_raw_data> on 2025-04-09 15:22:50.850962+00:00
[2025-04-09T15:22:53.101+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=152) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T15:22:53.103+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2025-04-09T15:22:53.104+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'extract_raw_data', 'manual__2025-04-09T15:22:50.850962+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmplxc21vt9']
[2025-04-09T15:22:53.106+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask extract_raw_data
[2025-04-09T15:22:53.243+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.extract_raw_data manual__2025-04-09T15:22:50.850962+00:00 [running]> on host 5a8aeda502d0
[2025-04-09T15:22:53.410+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T15:22:50.850962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T15:22:50.850962+00:00'
[2025-04-09T15:22:53.411+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-09T15:22:53.424+0000] {driven_data_pipeline.py:147} INFO - Started batch processing for 2025-04-09.
[2025-04-09T15:22:53.425+0000] {driven_data_pipeline.py:34} INFO - Created synthetic data for RO country code.
[2025-04-09T15:22:53.867+0000] {driven_data_pipeline.py:104} INFO - Written 861 records to the CSV file.
[2025-04-09T15:22:54.374+0000] {driven_data_pipeline.py:120} INFO - Added UUID to the dataset.
[2025-04-09T15:22:54.375+0000] {driven_data_pipeline.py:155} INFO - Finished batch processing 2025-04-09.
[2025-04-09T15:22:54.376+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-09T15:22:54.387+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-09T15:22:54.388+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=extract_raw_data, run_id=manual__2025-04-09T15:22:50.850962+00:00, execution_date=20250409T152250, start_date=20250409T152252, end_date=20250409T152254
[2025-04-09T15:22:54.483+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T15:22:54.514+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-09T15:22:54.545+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
