[2025-04-09T14:47:11.752+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T14:47:11.770+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted manual__2025-04-09T14:45:57.228215+00:00 [queued]>
[2025-04-09T14:47:11.778+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted manual__2025-04-09T14:45:57.228215+00:00 [queued]>
[2025-04-09T14:47:11.779+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-09T14:47:11.893+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-04-09 14:45:57.228215+00:00
[2025-04-09T14:47:11.899+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T14:47:11.900+0000] {standard_task_runner.py:72} INFO - Started process 214 to run task
[2025-04-09T14:47:11.901+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'manual__2025-04-09T14:45:57.228215+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpq9yiyhn9']
[2025-04-09T14:47:11.902+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask run_dbt_trusted
[2025-04-09T14:47:12.001+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted manual__2025-04-09T14:45:57.228215+00:00 [running]> on host 5a8aeda502d0
[2025-04-09T14:47:12.249+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T14:45:57.228215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T14:45:57.228215+00:00'
[2025-04-09T14:47:12.273+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-09T14:47:12.294+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T14:47:12.416+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-04-09T14:47:12.430+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T14:47:12.432+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-04-09T14:47:12.433+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-04-09T14:47:14.699+0000] {subprocess.py:93} INFO - [0m14:47:14  Running with dbt=1.8.0
[2025-04-09T14:47:15.005+0000] {subprocess.py:93} INFO - [0m14:47:15  Registered adapter: postgres=1.8.2
[2025-04-09T14:47:15.570+0000] {subprocess.py:93} INFO - [0m14:47:15  Found 9 models, 10 sources, 428 macros
[2025-04-09T14:47:15.577+0000] {subprocess.py:93} INFO - [0m14:47:15
[2025-04-09T14:47:16.042+0000] {subprocess.py:93} INFO - [0m14:47:16  Concurrency: 1 threads (target='dev')
[2025-04-09T14:47:16.043+0000] {subprocess.py:93} INFO - [0m14:47:16
[2025-04-09T14:47:16.054+0000] {subprocess.py:93} INFO - [0m14:47:16  1 of 4 START sql table model driven_trusted.non_pii_data ....................... [RUN]
[2025-04-09T14:47:25.735+0000] {subprocess.py:93} INFO - [0m14:47:25  1 of 4 OK created sql table model driven_trusted.non_pii_data .................. [[32mSELECT 113363[0m in 9.68s]
[2025-04-09T14:47:25.739+0000] {subprocess.py:93} INFO - [0m14:47:25  2 of 4 START sql table model driven_trusted.payment_data ....................... [RUN]
[2025-04-09T14:47:27.599+0000] {subprocess.py:93} INFO - [0m14:47:27  2 of 4 OK created sql table model driven_trusted.payment_data .................. [[32mSELECT 113363[0m in 1.86s]
[2025-04-09T14:47:27.602+0000] {subprocess.py:93} INFO - [0m14:47:27  3 of 4 START sql table model driven_trusted.pii_data ........................... [RUN]
[2025-04-09T14:47:32.380+0000] {subprocess.py:93} INFO - [0m14:47:32  3 of 4 OK created sql table model driven_trusted.pii_data ...................... [[32mSELECT 113363[0m in 4.78s]
[2025-04-09T14:47:32.383+0000] {subprocess.py:93} INFO - [0m14:47:32  4 of 4 START sql table model driven_trusted.technical_data ..................... [RUN]
[2025-04-09T14:47:34.981+0000] {subprocess.py:93} INFO - [0m14:47:34  4 of 4 OK created sql table model driven_trusted.technical_data ................ [[32mSELECT 113363[0m in 2.60s]
[2025-04-09T14:47:35.001+0000] {subprocess.py:93} INFO - [0m14:47:35
[2025-04-09T14:47:35.002+0000] {subprocess.py:93} INFO - [0m14:47:35  Finished running 4 table models in 0 hours 0 minutes and 19.42 seconds (19.42s).
[2025-04-09T14:47:35.070+0000] {subprocess.py:93} INFO - [0m14:47:35
[2025-04-09T14:47:35.071+0000] {subprocess.py:93} INFO - [0m14:47:35  [32mCompleted successfully[0m
[2025-04-09T14:47:35.073+0000] {subprocess.py:93} INFO - [0m14:47:35
[2025-04-09T14:47:35.074+0000] {subprocess.py:93} INFO - [0m14:47:35  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-04-09T14:47:36.020+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T14:47:36.162+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-09T14:47:36.163+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=run_dbt_trusted, run_id=manual__2025-04-09T14:45:57.228215+00:00, execution_date=20250409T144557, start_date=20250409T144711, end_date=20250409T144736
[2025-04-09T14:47:36.254+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T14:47:36.272+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T14:47:36.343+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
